"""GCC Tier-1 airport node definitions for crisis scenario packs."""

AIRPORTS_GCC = [
    {
        "id": "airport_kwi",
        "code": "KWI",
        "label": "Kuwait International Airport",
        "country": "Kuwait",
        "city": "Kuwait City",
        "hub_importance": 0.82,
        "cargo_relevance": 0.70,
        "fuel_relevance": 0.72,
    },
    {
        "id": "airport_ruh",
        "code": "RUH",
        "label": "King Khalid International Airport",
        "country": "Saudi Arabia",
        "city": "Riyadh",
        "hub_importance": 0.90,
        "cargo_relevance": 0.78,
        "fuel_relevance": 0.76,
    },
    {
        "id": "airport_dmm",
        "code": "DMM",
        "label": "King Fahd International Airport",
        "country": "Saudi Arabia",
        "city": "Dammam",
        "hub_importance": 0.84,
        "cargo_relevance": 0.80,
        "fuel_relevance": 0.83,
    },
    {
        "id": "airport_jed",
        "code": "JED",
        "label": "King Abdulaziz International Airport",
        "country": "Saudi Arabia",
        "city": "Jeddah",
        "hub_importance": 0.89,
        "cargo_relevance": 0.77,
        "fuel_relevance": 0.75,
    },
    {
        "id": "airport_dxb",
        "code": "DXB",
        "label": "Dubai International Airport",
        "country": "UAE",
        "city": "Dubai",
        "hub_importance": 0.98,
        "cargo_relevance": 0.91,
        "fuel_relevance": 0.88,
    },
    {
        "id": "airport_auh",
        "code": "AUH",
        "label": "Zayed International Airport",
        "country": "UAE",
        "city": "Abu Dhabi",
        "hub_importance": 0.92,
        "cargo_relevance": 0.83,
        "fuel_relevance": 0.84,
    },
    {
        "id": "airport_doh",
        "code": "DOH",
        "label": "Hamad International Airport",
        "country": "Qatar",
        "city": "Doha",
        "hub_importance": 0.95,
        "cargo_relevance": 0.88,
        "fuel_relevance": 0.86,
    },
    {
        "id": "airport_bah",
        "code": "BAH",
        "label": "Bahrain International Airport",
        "country": "Bahrain",
        "city": "Manama",
        "hub_importance": 0.79,
        "cargo_relevance": 0.73,
        "fuel_relevance": 0.71,
    },
    {
        "id": "airport_mct",
        "code": "MCT",
        "label": "Muscat International Airport",
        "country": "Oman",
        "city": "Muscat",
        "hub_importance": 0.80,
        "cargo_relevance": 0.69,
        "fuel_relevance": 0.70,
    },
]
